# Generated by Django 5.1.7 on 2025-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodidades',
            name='tipo_comodidade',
            field=models.CharField(choices=[('WIFI', 'Wi-Fi'), ('ESTACIONAMENTO', 'Estacionamento'), ('ACESSIBILIDADE', 'Acessibilidade'), ('BEBIDAS', 'Bebidas'), ('LANCHE', 'Lanche'), ('LAZER', 'Área de Lazer')], max_length=30),
        ),
    ]
