# Generated by Django 5.1.7 on 2025-11-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comodidades_tipo_comodidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comodidades',
            name='tipo_comodidade',
        ),
        migrations.AddField(
            model_name='comodidades',
            name='tipo_comodidade',
            field=models.ManyToManyField(to='core.facilidades'),
        ),
    ]
