# Generated by Django 5.1.7 on 2025-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facilidades_remove_comodidades_tipo_comodidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comodidades',
            name='tipo_comodidade',
        ),
        migrations.AddField(
            model_name='barbearia',
            name='comodidades',
            field=models.ManyToManyField(blank=True, to='core.comodidades'),
        ),
        migrations.AddField(
            model_name='comodidades',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Facilidades',
        ),
    ]
