# Generated by Django 5.1.7 on 2025-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_comodidades_tipo_comodidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comodidades',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
