# Generated by Django 5.1.7 on 2025-08-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, help_text='DOB', null=True, verbose_name='DOB'),
        ),
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, help_text='Cellphone', max_length=20, null=True, unique=True, verbose_name='cellphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
