# Generated by Django 5.1.7 on 2025-08-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_dob_user_cellphone_user_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
