# Generated by Django 5.1.7 on 2025-11-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comodidades_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_de_funcionamento',
            name='barbearia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.barbearia'),
        ),
        migrations.AddConstraint(
            model_name='horario_de_funcionamento',
            constraint=models.UniqueConstraint(fields=('barbearia', 'dia_da_semana'), name='unique_dia_por_barbearia'),
        ),
    ]
