# Generated by Django 5.1.7 on 2025-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
