# Generated by Django 5.1.7 on 2025-11-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horario_de_funcionamento_barbearia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_de_funcionamento',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.barbearia'),
        ),
    ]
