# Generated by Django 5.1.7 on 2025-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.CharField(choices=[('client', 'Cliente'), ('owner', 'Proprietário')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, help_text='Cellphone', max_length=11, null=True, unique=True, verbose_name='cellphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF', max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, help_text='Username', max_length=255, null=True, verbose_name='name'),
        ),
    ]
