# Generated by Django 5.1.7 on 2025-09-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_choice_alter_user_cellphone_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='choice',
            new_name='role',
        ),
    ]
