# Generated by Django 5.1.7 on 2025-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_is_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_facilidades', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Horario_de_funcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'segunda-feira'), (2, 'terça-feira'), (3, 'quarta-feira'), (4, 'quinta-feira'), (5, 'sexta-feira'), (6, 'sábado'), (0, 'domingo')])),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='info_da_barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_barbearia', models.CharField(max_length=200)),
                ('endereco_barbearia', models.CharField(max_length=200)),
                ('telefone_barbearia', models.CharField(max_length=11)),
                ('email_barbearia', models.EmailField(max_length=200)),
                ('descricao_barbearia', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicos_oferecidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_servico', models.CharField(max_length=30)),
                ('valor_do_servico', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tempo_estimado', models.DurationField()),
                ('descricao_do_servico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
