# Generated by Django 5.1.7 on 2025-10-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_facilidades_horario_de_funcionamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_barbearia', models.CharField(max_length=200)),
                ('CEP', models.CharField(max_length=10)),
                ('UF_da_barbearia', models.CharField(max_length=20)),
                ('cidade_da_barbearia', models.CharField(max_length=30)),
                ('endereco_da_barbearia', models.CharField(max_length=10)),
                ('telefone_da_barbearia', models.CharField(max_length=11)),
                ('email_da_barbearia', models.EmailField(max_length=200)),
                ('descricao_sobre_barbearia', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='facilidades',
            new_name='Comodidades',
        ),
        migrations.DeleteModel(
            name='info_da_barbearia',
        ),
        migrations.RenameField(
            model_name='comodidades',
            old_name='tipo_facilidades',
            new_name='tipo_comodidade',
        ),
    ]
