# Generated by Django 5.1.7 on 2025-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_barbearia_rename_facilidades_comodidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='cidade_da_barbearia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='endereco_da_barbearia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicos_oferecidos',
            name='valor_do_servico',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
