# Generated by Django 5.1.7 on 2025-10-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_barbearia_cidade_da_barbearia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='CNPJ_da_barbearia',
            field=models.CharField(default='1', max_length=14),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='nome_da_barbearia',
            field=models.CharField(max_length=100),
        ),
    ]
