# Generated by Django 5.1.7 on 2025-11-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_barbearia_cnpj_da_barbearia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='CEP',
            field=models.CharField(max_length=8),
        ),
    ]
