# Generated by Django 5.1.7 on 2025-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_barbearia_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos_oferecidos',
            name='tempo_estimado',
            field=models.PositiveIntegerField(help_text='Tempo em minutos'),
        ),
    ]
