# Generated by Django 5.1.7 on 2025-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_servicos_oferecidos_tempo_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos_oferecidos',
            name='tempo_estimado',
            field=models.PositiveIntegerField(default='1', help_text='Tempo em minutos'),
        ),
    ]
